version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - '8000:8000'

    depends_on:
      - db

    env_file:
      - .env

    volumes:
      - .:app

    working_dir: /app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - '5432:5432'

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: